app:
  jwt:
    access-secret: 01K85GAJVZ0BVS2S9PR7D561P01DSND38JG4701ND38JG4701K85GAJVZRZC561P01DPR7D561P01DSND38JG4701ND38JG4701K85GAJVZRZC561P01DSND38JG470
    refresh-secret: 01K85GAJVZ0BVS2S9PR7D561P01DSND38JG4701K85GAJVZRZC561PGESZ0BVS2S9GESZ0BVS2S9PR7D561P01D4701K85GAJVZRZC561PGESZRZC561PGESsSND38JG4
# 测试环境
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 10
  servlet:
    # 应用的访问路径
    context-path: /api
    session:
      cookie:
        http-only: true
spring:
  cloud:
    config:
      import-check:
        enabled: false
  data:
    redis:
      client-name:
      host: 59.110.152.124
      port: 6379
      password:
      database: 6
      timeout: 5s
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      max-lifetime: 120000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/started?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: e230u42o3og293jskbg3793uhi2bk3
#dynamic:
#  datasource:
#    slave1:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/started?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#      username: root
#      password: toor
#    slave2:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/started?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghaiity
#      username: root
#      password: toor
#

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
