app:
  jwt:
    accessSecret: 01K85GAJVZRZCWX1DSND38JG4701K85GAJVZRZCWX1DSND38JG47CWX1DSND38JG470
    refreshSecret: 01K85GAJVZ0BVS2S9PR7D561P01DSND38JG4701K85GAJVZRZC561P01DSND38JG470

#mybatis
mybatis-plus:
  mapper-locations: class2*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      id-type: ASSIGN_ID
    banner: false
  #原生配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
# 日志配置
logging:
  level:
    org:
      mybatis: debug
    com:
      example: trace
  file:
    name: logs/log.log

spring:
  messages:
    encoding: UTF-8
  cloud:
    config:
      import-check:
        enabled: false
  data:
    redis:
      client-name:
      host: localhost
      port: 6379
      password:
      database: 6
      timeout: 5s
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      max-lifetime: 120000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/started?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: e230u42o3og293jskbg3793uhi2bk3
