application:
  jwt-key: The longer this parameter is, system more secure it is;
# 测试环境
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 10
  servlet:
    # 应用的访问路径
    context-path: /
    session:
      cookie:
        http-only: true
spring:
  data:
    redis:
      client-name:
      host: localhost
      port: 6379
      password:
      database: 1
      timeout: 5s
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      max-lifetime: 120000
      jdbc-url: jdbc:mysql://localhost:3306/started?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/started?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: e230u42o3og293jskbg3793uhi2bk3

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
